# Generated by Django 4.1.4 on 2022-12-30 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_alter_planlist_id_alter_planlistdetail_id_and_more"),
        ("payablesubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenmoTransaction",
            fields=[
                (
                    "subscriptiontransaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="subscriptions.subscriptiontransaction",
                    ),
                ),
                (
                    "venmo_id",
                    models.PositiveBigIntegerField(editable=False, unique=True, verbose_name="Venmo ID"),
                ),
            ],
            bases=("subscriptions.subscriptiontransaction",),
        ),
    ]
