# Generated by Django 4.1.4 on 2023-01-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_alter_planlist_id_alter_planlistdetail_id_and_more"),
        ("payablesubs", "0002_venmotransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "subscriptiontransaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="subscriptions.subscriptiontransaction",
                    ),
                ),
                (
                    "host_payment_id",
                    models.PositiveBigIntegerField(
                        editable=False,
                        help_text="the host's (i.e.: Venmo) identifier for this payment",
                        unique=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("VENMO", "Venmo"), ("CASH", "Cash")],
                        default=None,
                        help_text="the method of payment used",
                        max_length=6,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="property bag to store additional payment details in",
                        null=True,
                    ),
                ),
            ],
            bases=("subscriptions.subscriptiontransaction",),
        ),
        migrations.DeleteModel(
            name="VenmoTransaction",
        ),
    ]
